### ISSUE TITLE
Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-memory-alert

### ISSUE THREAD

**Issue by ghost** [Wizcorp/cordova-plugin-memory-alert#1]
I am getting following issue during plugin add:

Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-memory-alert

**Comment by rejhgadellaabsl** [comment]
+1

**Comment by rejhgadellaabsl** [comment]
Same here.

$ cordova plugin add cordova-plugin-memory-alert
Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-memory-alert

**Comment by tbrebant** [comment]
Sorry for the late answer. It's pretty simple: the package is not on npm. You have to add it with:

```
cordova plugin add https://github.com/Wizcorp/cordova-plugin-memory-alert
```

instead of `cordova plugin add cordova-plugin-memory-alert`.

To prevent other users to have the same problem I'm going to publish it now.

**Comment by tbrebant** [comment]
Published on npm, closing the issue.
